class FunctionUsageError(Exception):
    pass


class DataError(Exception):
    pass
